name: PHP Package Tests
on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: immediate-media/github-actions-public/.github/workflows/php-package-testing.yml@main
    with:
      php-version: '8.2'
