name: PHP Package Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-workflow:
    uses: immediate-media/github-actions/.github/workflows/dotnet-pkg-vuln-chk.yml@feature/php-workflow
    with:
      php-version: '8.2'
